apiVersion: v1 
kind: Service
metadata:
  name: mongoexpress-svc
spec:
  selector:
      app: mongo-express
  type: LoadBalancer    
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31000
